import type { HashBatch, QrToken, TraceEvent, TraceLot, TraceReport } from './traceabilityTypes';

export const DIAGNOSTIC_MAP_ASSET = 'mock://state-college-pa-apple-orchard-map';

export interface MockTraceFarm {
  id: string;
  name: string;
  region: string;
  county: string;
  coordinates: string;
  lat: number;
  lng: number;
  orchardBlock: string;
  areaHectares: number;
  crops: string[];
  manager: string;
  farmerCount: number;
  fieldAgent: string;
  organicStatus: 'Full organic' | 'Partial organic' | 'Conventional transition';
  sensorCoverage: number;
  whatsappCoverage: number;
  labStatus: string;
  lastDiagnosticAt: string;
  healthPercent: number;
  totalCells: number;
  healthyCells: number;
  problemAreas: number;
  criticalAreas: number;
  satelliteImages: number;
  activeWarnings: string[];
}

export const MOCK_TRACE_FARMS: MockTraceFarm[] = [
  {
    id: 'pa-centre-hall-honeycrisp',
    name: 'Centre Hall Honeycrisp Block',
    region: 'Centre Hall, PA',
    county: 'Centre County',
    coordinates: '40.8470, -77.6860',
    lat: 40.847,
    lng: -77.686,
    orchardBlock: 'Block A2 - high-density trellis',
    areaHectares: 8.6,
    crops: ['Honeycrisp', 'GoldRush'],
    manager: 'Nittany Valley Orchard Network',
    farmerCount: 7,
    fieldAgent: 'Maya C.',
    organicStatus: 'Partial organic',
    sensorCoverage: 88,
    whatsappCoverage: 96,
    labStatus: 'Residue panel scheduled',
    lastDiagnosticAt: '2026-05-24T14:15:00.000Z',
    healthPercent: 92,
    totalCells: 191,
    healthyCells: 176,
    problemAreas: 15,
    criticalAreas: 3,
    satelliteImages: 12,
    activeWarnings: ['Apple scab infection window', 'Codling moth trap spike', 'Dry ridge row'],
  },
  {
    id: 'pa-boalsburg-gala',
    name: 'Boalsburg Gala Orchard',
    region: 'Boalsburg, PA',
    county: 'Centre County',
    coordinates: '40.7750, -77.7920',
    lat: 40.775,
    lng: -77.792,
    orchardBlock: 'South slope blocks B1-B3',
    areaHectares: 6.1,
    crops: ['Gala', 'Cortland'],
    manager: 'Happy Valley Fruit Co-op',
    farmerCount: 5,
    fieldAgent: 'Ethan M.',
    organicStatus: 'Full organic',
    sensorCoverage: 81,
    whatsappCoverage: 91,
    labStatus: 'Organic certificate and water test uploaded',
    lastDiagnosticAt: '2026-05-23T11:05:00.000Z',
    healthPercent: 96,
    totalCells: 154,
    healthyCells: 148,
    problemAreas: 6,
    criticalAreas: 1,
    satelliteImages: 14,
    activeWarnings: ['Bloom thinning follow-up', 'Low calcium watch'],
  },
  {
    id: 'pa-bellefonte-cider',
    name: 'Bellefonte Cider Apple Line',
    region: 'Bellefonte, PA',
    county: 'Centre County',
    coordinates: '40.9130, -77.7780',
    lat: 40.913,
    lng: -77.778,
    orchardBlock: 'Heritage cider rows C4-C8',
    areaHectares: 10.4,
    crops: ['Cider blend', 'Stayman', 'Rome'],
    manager: 'Spring Creek Cider Buyers',
    farmerCount: 9,
    fieldAgent: 'Ava R.',
    organicStatus: 'Conventional transition',
    sensorCoverage: 72,
    whatsappCoverage: 84,
    labStatus: 'Brix test uploaded; residue panel due',
    lastDiagnosticAt: '2026-05-22T15:40:00.000Z',
    healthPercent: 84,
    totalCells: 218,
    healthyCells: 183,
    problemAreas: 35,
    criticalAreas: 8,
    satelliteImages: 10,
    activeWarnings: ['Fire blight blossom risk', 'Weigh ticket missing', 'Cider grade split pending'],
  },
  {
    id: 'pa-warriors-mark-fuji',
    name: 'Warriors Mark Fuji Ridge',
    region: 'Warriors Mark, PA',
    county: 'Huntingdon County',
    coordinates: '40.7030, -78.1300',
    lat: 40.703,
    lng: -78.13,
    orchardBlock: 'Ridge block F1',
    areaHectares: 5.2,
    crops: ['Fuji', 'Pink Lady'],
    manager: 'Allegheny Apple Supply',
    farmerCount: 4,
    fieldAgent: 'Noah K.',
    organicStatus: 'Partial organic',
    sensorCoverage: 63,
    whatsappCoverage: 78,
    labStatus: 'No lab proof uploaded',
    lastDiagnosticAt: '2026-05-21T09:35:00.000Z',
    healthPercent: 79,
    totalCells: 132,
    healthyCells: 104,
    problemAreas: 28,
    criticalAreas: 9,
    satelliteImages: 9,
    activeWarnings: ['Location handoff gap', 'Bitter rot risk', 'Spray log reconciliation'],
  },
  {
    id: 'pa-port-matilda-goldrush',
    name: 'Port Matilda GoldRush Block',
    region: 'Port Matilda, PA',
    county: 'Centre County',
    coordinates: '40.8000, -78.0500',
    lat: 40.8,
    lng: -78.05,
    orchardBlock: 'Block G5 - late harvest',
    areaHectares: 4.8,
    crops: ['GoldRush', 'Enterprise'],
    manager: 'Nittany Valley Orchard Network',
    farmerCount: 3,
    fieldAgent: 'Sofia L.',
    organicStatus: 'Full organic',
    sensorCoverage: 79,
    whatsappCoverage: 89,
    labStatus: 'Organic certificate uploaded; firmness test pending',
    lastDiagnosticAt: '2026-05-25T08:10:00.000Z',
    healthPercent: 94,
    totalCells: 119,
    healthyCells: 112,
    problemAreas: 7,
    criticalAreas: 1,
    satelliteImages: 13,
    activeWarnings: ['Irrigation valve review', 'Mating disruption dispenser check'],
  },
];

export const MOCK_TRACE_LOT_ID = 'mock-centre-hall-honeycrisp-20260912';

const lotMetadata = {
  mock_source: 'Traceability.pdf data points adapted to a State College, Pennsylvania apple pilot',
  farm_id: 'pa-centre-hall-honeycrisp',
  farm_name: 'Centre Hall Honeycrisp Block',
  farm_location: 'Centre Hall, PA; 40.8470, -77.6860',
  county: 'Centre County',
  orchard_block: 'Block A2 - high-density trellis',
  seed_type: 'Honeycrisp scion on M.9 rootstock; nursery tag and block map uploaded',
  grown_method: 'Orchard block mapping, bloom and degree-day models, satellite vigor checks, trap counts, scout photos, and field-agent verification',
  organic_status: 'Partial organic / IPM',
  inorganic_materials: 'Kaolin clay, mating disruption, sulfur, and lime-sulfur prioritized; conventional rescue input allowed only after threshold-based scout approval',
  seller_node: {
    yield: '164,800 lb marketable apples forecast; final packout pending harvest',
    grade: 'Forecast: US Extra Fancy 58%, Fancy 31%, Processing 11%',
    quality: 'Brix, pressure, starch index, and residue panel scheduled before buyer release',
    how_organic: 'Partial organic/IPM: organic-compatible controls first, every rescue material logged with weather and scout evidence',
    harvest_date: 'Forecast: 2026-09-12',
    farm_location: 'Centre Hall, PA; 40.8470, -77.6860',
    seed_type: 'Honeycrisp on M.9 rootstock; nursery tag uploaded',
    disease_history: 'Apple scab infection window, codling moth trap spike, and localized dry ridge row under review',
  },
  diagnostic_summary: {
    farm_health: '92%',
    healthy_cells: 176,
    total_cells: 191,
    problem_areas: 15,
    critical_areas: 3,
    analyzed_at: '2026-05-24T14:15:00.000Z',
    satellite_images: 12,
    detected_issues: ['Apple scab infection window', 'Codling moth trap spike', 'Dry ridge row'],
  },
  crop_model: {
    current_week: 'Week 18: fruit set and thinning verification',
    stage: 'Dormancy to harvest apple block monitoring',
    warning_source: 'Degree-day model + weather station + trap counts + satellite vigor',
    farmer_photo_task: 'Capture blossom cluster, fruitlet thinning, leaf lesion, and trap-count photos from flagged rows',
    suggestion_loop: 'Prioritize IPM/organic-compatible controls, irrigation checks, and scout confirmation before any threshold-based rescue input',
    progress_tracking: 'Track canopy vigor, disease lesions, fruit set, trap counts, and post-action recovery after each recommendation',
    weekly_plan: [
      { week: '1-4', stage: 'Dormant pruning', ideal: 'Pruned canopy, block map confirmed, no standing debris', signal: 'Field-agent block photo and polygon check', status: 'complete' },
      { week: '5-8', stage: 'Green tip to pink', ideal: 'Scab prevention window covered and traps installed', signal: 'Weather station, degree days, scout photos', status: 'complete' },
      { week: '9-12', stage: 'Bloom', ideal: 'Pollination strong, fire blight risk monitored', signal: 'Bloom photos, humidity, blossom blight model', status: 'complete' },
      { week: '13-18', stage: 'Fruit set / thinning', ideal: 'Uniform fruitlets, low pest pressure, irrigation stable', signal: 'Satellite vigor, trap counts, soil moisture', status: 'active' },
      { week: '19-28', stage: 'Summer cover / quality build', ideal: 'Calcium program, disease watch, packout forecast', signal: 'Scout routes, residue log, brix/pressure samples', status: 'planned' },
      { week: '29-34', stage: 'Harvest and packout', ideal: 'Harvest by maturity band, grade, pack, and QR release', signal: 'Harvest tickets, packhouse grade sheet, residue panel', status: 'planned' },
    ],
  },
  disease_model: {
    risk_level: 'Medium: weather-driven scab and codling moth pressure',
    likely_diseases: ['Apple scab', 'Fire blight watch', 'Cedar apple rust', 'Codling moth', 'Bitter rot watch'],
    signals_used: ['Rain and leaf-wetness hours', 'degree days', 'trap counts', 'satellite canopy vigor', 'nearby orchard alerts'],
    collection_plan: 'Collect leaf lesion, blossom, fruitlet, trap-card, and irrigation-row photos at mapped warning rows',
    advice_channel: 'App scout task + WhatsApp field-agent alert',
  },
  grade_quality_yield: {
    harvest_map: 'Harvest Honeycrisp by maturity band: red-color rows first, then shaded rows, then processing picks',
    cross_verification: 'Mobile app geo-tagged bins, packhouse grade sheet, cold-storage entry, and buyer receiving record',
    grade_a_spots: 'Highest Extra Fancy forecast along upper ridge rows with stable vigor',
    grade_split: 'US Extra Fancy 58%, Fancy 31%, Processing 11%',
    yield_estimate: '164,800 lb marketable apples forecast',
  },
  evidence_coverage: {
    farm_polygon: 100,
    seed_declaration: 92,
    organic_inputs: 78,
    farmer_photos: 86,
    lab_tests: 56,
    grade_yield: 79,
    disease_history: 83,
    qr_passport: 91,
  },
};

function makeLot(overrides: Partial<TraceLot> & { id: string; metadata?: Record<string, unknown> }): TraceLot {
  return {
    organization_id: 'mock-wrkfarm-pa-org',
    lot_code: overrides.id.toUpperCase(),
    crop: 'apples',
    variety: 'Honeycrisp',
    season: '2026 apple season',
    production_area_hectares: 1,
    initial_quantity: 100000,
    current_quantity: 95000,
    quantity_unit: 'lb',
    status: 'planted',
    compliance_status: 'ready',
    evidence_score: 80,
    risk_score: 20,
    created_at: '2026-05-24T14:15:00.000Z',
    updated_at: '2026-05-24T15:00:00.000Z',
    ...overrides,
    metadata: {
      ...lotMetadata,
      ...overrides.metadata,
      seller_node: {
        ...lotMetadata.seller_node,
        ...(overrides.metadata?.seller_node as Record<string, unknown> | undefined),
      },
      diagnostic_summary: {
        ...lotMetadata.diagnostic_summary,
        ...(overrides.metadata?.diagnostic_summary as Record<string, unknown> | undefined),
      },
      crop_model: {
        ...lotMetadata.crop_model,
        ...(overrides.metadata?.crop_model as Record<string, unknown> | undefined),
      },
      disease_model: {
        ...lotMetadata.disease_model,
        ...(overrides.metadata?.disease_model as Record<string, unknown> | undefined),
      },
      grade_quality_yield: {
        ...lotMetadata.grade_quality_yield,
        ...(overrides.metadata?.grade_quality_yield as Record<string, unknown> | undefined),
      },
      evidence_coverage: {
        ...lotMetadata.evidence_coverage,
        ...(overrides.metadata?.evidence_coverage as Record<string, unknown> | undefined),
      },
    },
  };
}

export const MOCK_TRACE_LOTS: TraceLot[] = [
  makeLot({
    id: MOCK_TRACE_LOT_ID,
    lot_code: 'CENTRE-HALL-HONEYCRISP-20260912',
    crop: 'apples',
    variety: 'Honeycrisp / GoldRush',
    season: '2026 apple season',
    production_area_hectares: 8.6,
    initial_quantity: 171200,
    current_quantity: 164800,
    status: 'quality_checked',
    compliance_status: 'ready',
    evidence_score: 88,
    risk_score: 18,
  }),
  makeLot({
    id: 'mock-boalsburg-gala-20260918',
    lot_code: 'BOALSBURG-GALA-20260918',
    crop: 'apples',
    variety: 'Gala / Cortland',
    production_area_hectares: 6.1,
    initial_quantity: 121600,
    current_quantity: 118200,
    status: 'stored',
    compliance_status: 'verified',
    evidence_score: 94,
    risk_score: 8,
    created_at: '2026-05-23T11:05:00.000Z',
    updated_at: '2026-05-23T12:20:00.000Z',
    metadata: {
      farm_id: 'pa-boalsburg-gala',
      farm_name: 'Boalsburg Gala Orchard',
      farm_location: 'Boalsburg, PA; 40.7750, -77.7920',
      county: 'Centre County',
      orchard_block: 'South slope blocks B1-B3',
      seed_type: 'Gala and Cortland scion blocks on M.26 rootstock; nursery tags and organic seedling records uploaded',
      organic_status: 'Full organic',
      inorganic_materials: 'No conventional rescue material recorded; sulfur, neem oil, mating disruption, and compost tea logs uploaded',
      seller_node: {
        yield: '118,200 lb marketable apples forecast',
        grade: 'Forecast: US Extra Fancy 63%, Fancy 29%, Processing 8%',
        quality: 'Organic certificate, water test, scout sheet, and maturity plan uploaded',
        how_organic: 'Full organic program with uploaded certificate, compost records, sulfur cover, and mating-disruption proof',
        harvest_date: 'Forecast: 2026-09-18',
        farm_location: 'Boalsburg, PA; 40.7750, -77.7920',
        seed_type: 'Gala/Cortland on M.26 rootstock',
        disease_history: 'Low disease pressure; bloom thinning and calcium watch open',
      },
      diagnostic_summary: { farm_health: '96%', healthy_cells: 148, total_cells: 154, problem_areas: 6, critical_areas: 1, satellite_images: 14, detected_issues: ['Bloom thinning follow-up', 'Low calcium watch'] },
      disease_model: {
        risk_level: 'Low: organic records complete, localized calcium watch',
        likely_diseases: ['Apple scab watch', 'Cedar apple rust watch'],
        collection_plan: 'Upload calcium spray log and fruitlet size photos from two south-slope rows',
      },
      evidence_coverage: { seed_declaration: 98, organic_inputs: 96, farmer_photos: 90, lab_tests: 84, grade_yield: 88, disease_history: 89, qr_passport: 96 },
    },
  }),
  makeLot({
    id: 'mock-bellefonte-cider-20260920',
    lot_code: 'BELLEFONTE-CIDER-20260920',
    crop: 'apples',
    variety: 'Stayman / Rome / cider blend',
    production_area_hectares: 10.4,
    initial_quantity: 201000,
    current_quantity: 193500,
    status: 'harvested',
    compliance_status: 'review_needed',
    evidence_score: 73,
    risk_score: 36,
    created_at: '2026-05-22T15:40:00.000Z',
    updated_at: '2026-05-22T16:05:00.000Z',
    metadata: {
      farm_id: 'pa-bellefonte-cider',
      farm_name: 'Bellefonte Cider Apple Line',
      farm_location: 'Bellefonte, PA; 40.9130, -77.7780',
      county: 'Centre County',
      orchard_block: 'Heritage cider rows C4-C8',
      seed_type: 'Mixed cider-variety rows; rootstock tags partially uploaded',
      organic_status: 'Conventional transition',
      inorganic_materials: 'One fire blight rescue material declaration requires buyer review; residue panel due',
      seller_node: {
        yield: '193,500 lb cider apples forecast; final press-weight not reconciled',
        grade: 'Cider grade 78%, table grade 14%, cull 8%',
        quality: 'Brix report uploaded; residue panel and final weigh ticket pending',
        how_organic: 'Conventional transition with IPM logs; rescue input declaration requires review',
        harvest_date: 'Forecast: 2026-09-20',
        farm_location: 'Bellefonte, PA; 40.9130, -77.7780',
        seed_type: 'Stayman/Rome/cider blend; rootstock proof partial',
        disease_history: 'Fire blight blossom risk, cider grade split pending, weigh ticket missing',
      },
      diagnostic_summary: { farm_health: '84%', healthy_cells: 183, total_cells: 218, problem_areas: 35, critical_areas: 8, satellite_images: 10, detected_issues: ['Fire blight blossom risk', 'Weigh ticket missing', 'Cider grade split pending'] },
      disease_model: {
        risk_level: 'Medium-high: fire blight blossom window and missing residue proof',
        likely_diseases: ['Fire blight', 'Bitter rot watch', 'Sooty blotch/flyspeck'],
        collection_plan: 'Capture blossom-blight row photos, upload spray log, and attach residue panel before buyer release',
      },
      evidence_coverage: { seed_declaration: 62, organic_inputs: 54, farmer_photos: 76, lab_tests: 48, grade_yield: 64, disease_history: 72, qr_passport: 70 },
    },
  }),
  makeLot({
    id: 'mock-warriors-mark-fuji-20260925',
    lot_code: 'WARRIORS-MARK-FUJI-20260925',
    crop: 'apples',
    variety: 'Fuji / Pink Lady',
    production_area_hectares: 5.2,
    initial_quantity: 104400,
    current_quantity: 98600,
    status: 'planted',
    compliance_status: 'incomplete',
    evidence_score: 60,
    risk_score: 49,
    created_at: '2026-05-21T09:35:00.000Z',
    updated_at: '2026-05-21T10:20:00.000Z',
    metadata: {
      farm_id: 'pa-warriors-mark-fuji',
      farm_name: 'Warriors Mark Fuji Ridge',
      farm_location: 'Warriors Mark, PA; 40.7030, -78.1300',
      county: 'Huntingdon County',
      orchard_block: 'Ridge block F1',
      seed_type: 'Fuji and Pink Lady scions on semi-dwarf rootstock; nursery tag photo missing for one row',
      organic_status: 'Partial organic / IPM',
      inorganic_materials: 'Spray log reconciliation required; buyer report blocked until row-level input records match scout notes',
      seller_node: {
        yield: '98,600 lb forecast; harvest not finalized',
        grade: 'Forecast only: Extra Fancy 42%, Fancy 37%, Processing 21%',
        quality: 'No residue panel uploaded; firmness and starch tests pending',
        how_organic: 'Partial organic/IPM, but spray log reconciliation is still open',
        harvest_date: 'Forecast: 2026-09-25',
        farm_location: 'Warriors Mark, PA; 40.7030, -78.1300',
        seed_type: 'Fuji/Pink Lady on semi-dwarf rootstock; proof incomplete',
        disease_history: 'Bitter rot risk, location handoff gap, and spray-log issue',
      },
      diagnostic_summary: { farm_health: '79%', healthy_cells: 104, total_cells: 132, problem_areas: 28, critical_areas: 9, satellite_images: 9, detected_issues: ['Location handoff gap', 'Bitter rot risk', 'Spray log reconciliation'] },
      disease_model: {
        risk_level: 'High: missing input proof and bitter rot weather window',
        likely_diseases: ['Bitter rot', 'Apple scab watch', 'Codling moth'],
        collection_plan: 'Upload row-level spray log, trap photos, and two geo-tagged field-agent checks before QR release',
      },
      evidence_coverage: { seed_declaration: 48, organic_inputs: 42, farmer_photos: 61, lab_tests: 18, grade_yield: 44, disease_history: 59, qr_passport: 50 },
    },
  }),
  makeLot({
    id: 'mock-port-matilda-goldrush-20261005',
    lot_code: 'PORT-MATILDA-GOLDRUSH-20261005',
    crop: 'apples',
    variety: 'GoldRush / Enterprise',
    production_area_hectares: 4.8,
    initial_quantity: 91800,
    current_quantity: 88900,
    status: 'quality_checked',
    compliance_status: 'ready',
    evidence_score: 90,
    risk_score: 14,
    created_at: '2026-05-25T08:10:00.000Z',
    updated_at: '2026-05-25T09:00:00.000Z',
    metadata: {
      farm_id: 'pa-port-matilda-goldrush',
      farm_name: 'Port Matilda GoldRush Block',
      farm_location: 'Port Matilda, PA; 40.8000, -78.0500',
      county: 'Centre County',
      orchard_block: 'Block G5 - late harvest',
      seed_type: 'GoldRush and Enterprise disease-resistant varieties; nursery tags uploaded',
      organic_status: 'Full organic',
      inorganic_materials: 'No conventional rescue material recorded; mating disruption dispenser audit open',
      seller_node: {
        yield: '88,900 lb late-harvest apples forecast',
        grade: 'Forecast: US Extra Fancy 61%, Fancy 30%, Processing 9%',
        quality: 'Organic certificate uploaded; firmness and starch index tests pending',
        how_organic: 'Full organic program with compost, sulfur, mating disruption, and disease-resistant variety documentation',
        harvest_date: 'Forecast: 2026-10-05',
        farm_location: 'Port Matilda, PA; 40.8000, -78.0500',
        seed_type: 'GoldRush/Enterprise disease-resistant blocks',
        disease_history: 'Irrigation valve review and dispenser check; no critical disease spread',
      },
      diagnostic_summary: { farm_health: '94%', healthy_cells: 112, total_cells: 119, problem_areas: 7, critical_areas: 1, satellite_images: 13, detected_issues: ['Irrigation valve review', 'Mating disruption dispenser check'] },
      disease_model: {
        risk_level: 'Low: disease-resistant variety block with one irrigation review',
        likely_diseases: ['Apple scab watch', 'Bitter rot watch'],
        collection_plan: 'Confirm dispenser count and upload one irrigation-valve photo before buyer packet export',
      },
      evidence_coverage: { seed_declaration: 98, organic_inputs: 94, farmer_photos: 87, lab_tests: 72, grade_yield: 86, disease_history: 88, qr_passport: 94 },
    },
  }),
];

function makeEventsForLot(lot: TraceLot): TraceEvent[] {
  const metadata = lot.metadata ?? {};
  const diagnosticSummary = metadata.diagnostic_summary as Record<string, unknown> | undefined;
  return [
    {
      id: `${lot.id}-plot-registered`,
      organization_id: lot.organization_id,
      event_type: 'plot_registered',
      event_time: '2026-02-15T09:10:00.000Z',
      farm_id: String(metadata.farm_id ?? 'mock-pa-orchard'),
      lot_id: lot.id,
      location_json: {
        farm_location: metadata.farm_location,
        county: metadata.county,
        orchard_block: metadata.orchard_block,
        source: 'mock_state_college_orchard_dashboard',
      },
      quantity_unit: lot.quantity_unit,
      cte_type: 'commission',
      kde_payload: { farm_location: metadata.farm_location, seed_type: metadata.seed_type, orchard_block: metadata.orchard_block },
      confidence_score: 86,
      event_hash: `${lot.id}-hash-plot`,
      hash_status: 'batched',
      notes: 'Apple orchard block registered with polygon, row, rootstock, and buyer-origin metadata.',
      created_at: '2026-02-15T09:10:00.000Z',
      evidence: [{ evidence_type: 'field_agent_verification', title: 'Orchard block and row verification', uri: DIAGNOSTIC_MAP_ASSET, confidence_score: 86 }],
    },
    {
      id: `${lot.id}-crop-planted`,
      organization_id: lot.organization_id,
      event_type: 'crop_planted',
      event_time: '2026-03-30T08:30:00.000Z',
      lot_id: lot.id,
      quantity_in: Math.max(1, Math.round((lot.production_area_hectares ?? 1) * 120)),
      quantity_unit: 'tree-row units',
      cte_type: 'transformation',
      kde_payload: { seed_type: metadata.seed_type, crop_model: 'apple dormancy-to-harvest phenology model' },
      confidence_score: 78,
      previous_event_hash: `${lot.id}-hash-plot`,
      event_hash: `${lot.id}-hash-plant`,
      hash_status: 'batched',
      notes: 'Rootstock, variety, pruning, and early-season stage captured.',
      created_at: '2026-03-30T08:30:00.000Z',
      evidence: [{ evidence_type: 'survey', title: 'Rootstock, variety, and pruning declaration', confidence_score: 78 }],
    },
    {
      id: `${lot.id}-field-observed`,
      organization_id: lot.organization_id,
      event_type: 'field_observed',
      event_time: String(diagnosticSummary?.analyzed_at ?? lot.created_at),
      lot_id: lot.id,
      quantity_unit: lot.quantity_unit,
      cte_type: 'observation',
      kde_payload: diagnosticSummary,
      confidence_score: Math.round(lot.evidence_score),
      previous_event_hash: `${lot.id}-hash-plant`,
      event_hash: `${lot.id}-hash-observed`,
      hash_status: 'batched',
      notes: 'Satellite vigor, weather-model, trap-count, and scout-warning summary captured.',
      created_at: lot.created_at,
      evidence: [{ evidence_type: 'satellite_diagnostic', title: 'State College orchard map and warning evidence', uri: DIAGNOSTIC_MAP_ASSET, confidence_score: Math.round(lot.evidence_score) }],
    },
    {
      id: `${lot.id}-input-applied`,
      organization_id: lot.organization_id,
      event_type: 'input_applied',
      event_time: '2026-05-20T07:30:00.000Z',
      lot_id: lot.id,
      quantity_unit: lot.quantity_unit,
      cte_type: 'observation',
      kde_payload: { organic_status: metadata.organic_status, inputs: metadata.inorganic_materials },
      confidence_score: Math.max(50, Math.round(lot.evidence_score - 8)),
      previous_event_hash: `${lot.id}-hash-observed`,
      event_hash: `${lot.id}-hash-input`,
      hash_status: 'batched',
      notes: 'IPM, organic-compatible, and threshold-based input evidence captured for buyer review.',
      created_at: '2026-05-20T07:30:00.000Z',
      evidence: [{ evidence_type: 'survey', title: 'IPM and input log', confidence_score: Math.max(50, Math.round(lot.evidence_score - 10)) }],
    },
    {
      id: `${lot.id}-quality-checked`,
      organization_id: lot.organization_id,
      event_type: 'quality_checked',
      event_time: lot.updated_at ?? lot.created_at,
      lot_id: lot.id,
      quantity_in: lot.initial_quantity,
      quantity_out: lot.current_quantity,
      quantity_unit: lot.quantity_unit,
      cte_type: 'inspection',
      kde_payload: (metadata.seller_node ?? {}) as Record<string, unknown>,
      confidence_score: Math.max(55, Math.round(lot.evidence_score - 4)),
      previous_event_hash: `${lot.id}-hash-input`,
      event_hash: `${lot.id}-hash-quality`,
      hash_status: 'batched',
      notes: 'Grade, quality, yield, maturity, and seller-node values captured.',
      created_at: lot.updated_at ?? lot.created_at,
      evidence: [{ evidence_type: 'lab_report', title: 'Packout, maturity, or residue record', confidence_score: Math.max(45, Math.round(lot.evidence_score - 12)) }],
    },
  ];
}

export const MOCK_TRACE_EVENTS: TraceEvent[] = MOCK_TRACE_LOTS.flatMap(makeEventsForLot);

export const MOCK_HASH_BATCHES: HashBatch[] = [
  {
    id: 'mock-pa-apple-hash-batch-20260525',
    organization_id: 'mock-wrkfarm-pa-org',
    batch_date: '2026-05-25',
    event_count: MOCK_TRACE_EVENTS.length,
    merkle_root: '5e3a6d0d48c221dd8f46b7046d6fd78d2d7d1d9d53c280f26c18b767c4e6b5aa',
    algorithm: 'sha256-merkle-v1',
    event_hashes: MOCK_TRACE_EVENTS.map((event) => event.event_hash),
    polygon_tx_hash: null,
    created_at: '2026-05-25T23:59:00.000Z',
  },
];

export const MOCK_QR_TOKENS: QrToken[] = MOCK_TRACE_LOTS.map((lot) => ({
  id: `${lot.id}-qr-token`,
  organization_id: lot.organization_id,
  lot_id: lot.id,
  token: `wrk-${lot.lot_code.toLowerCase()}`,
  public_slug: `lot-${lot.lot_code.toLowerCase()}`,
  status: 'active',
  scan_count: lot.id === MOCK_TRACE_LOT_ID ? 0 : Math.round(lot.evidence_score / 3),
  created_at: lot.updated_at ?? lot.created_at,
}));

export const MOCK_QR_TOKEN: QrToken = MOCK_QR_TOKENS[0];

export const MOCK_TRACE_REPORTS: TraceReport[] = MOCK_TRACE_LOTS.map((lot) => ({
  id: `${lot.id}-buyer-audit-report`,
  organization_id: lot.organization_id,
  lot_id: lot.id,
  report_type: 'buyer_audit',
  title: `${lot.lot_code} buyer audit`,
  status: 'generated',
  created_at: lot.updated_at ?? lot.created_at,
  report_json: {
    seller_node: lot.metadata?.seller_node,
    diagnostic_summary: lot.metadata?.diagnostic_summary,
    organic_production: lot.metadata?.crop_model,
    grade_quality_yield: lot.metadata?.grade_quality_yield,
    caveats: [
      'Mock State College apple data adapted from the Traceability.pdf buyer data points for UI and workflow validation.',
      'Organic, residue, maturity, and packout claims need uploaded certificates, lab reports, or buyer records before production use.',
    ],
  },
}));

export function getMockLotBundle(lotId: string) {
  const lot = MOCK_TRACE_LOTS.find((item) => item.id === lotId) ?? MOCK_TRACE_LOTS[0];
  return {
    lot,
    events: MOCK_TRACE_EVENTS.filter((event) => event.lot_id === lot.id),
    reports: MOCK_TRACE_REPORTS.filter((report) => report.lot_id === lot.id),
    token: MOCK_QR_TOKENS.find((token) => token.lot_id === lot.id) ?? null,
  };
}

export function buildMockPassport(tokenValue?: string) {
  const token = MOCK_QR_TOKENS.find((item) => item.public_slug === tokenValue || item.token === tokenValue) ?? MOCK_QR_TOKEN;
  const lot = MOCK_TRACE_LOTS.find((item) => item.id === token.lot_id) ?? MOCK_TRACE_LOTS[0];
  return {
    token: {
      public_slug: token.public_slug,
      status: token.status,
    },
    lot,
    events: MOCK_TRACE_EVENTS.filter((event) => event.lot_id === lot.id),
    hash_batches: MOCK_HASH_BATCHES,
    caveats: [
      'Mock traceability passport for a State College, Pennsylvania apple pilot.',
      'Remote-sensing, weather, scout, and trap-count evidence supports review but does not replace lab, certification, or buyer receiving verification.',
    ],
  };
}
